### ISSUE TITLE
Weird bugs?

### ISSUE THREAD

**Issue by derenrich** [fuddl/wd#107]
So in the last few weeks the extension has started acting very odd. Really it hasn't worked properly for a while.

## Accidental edits?

For example:

- I go to https://twitter.com/hardmaru
- The side bar shows Q113563433
- Q113563433 was made by another user of the extension that is clearly also broken (and they didn't notice?)
- See screenshot

![wd bug](https://user-images.githubusercontent.com/79513/204607898-64475082-af27-439f-bfc3-aa9103196dba.png)

But other things are also acting up.

## Adding social media links

Another example:
 - Go to https://www.vt.edu/
 - Click add statement
 - Links appear to add some social media 
 - Clicking on the links does nothing
 - See screenshot

![vt bug](https://user-images.githubusercontent.com/79513/204610251-63dbb41a-3959-486a-8dab-26b7fa246080.png)

These may be disconnected issues but they only really started happening recently. And just generally things are slower/less reliable now. Or maybe it's in my head.

**Comment by derenrich** [comment]
I think maybe the first issue is caused by the sidepanel getting stuck on a previous page? Like it's not updating when I change pages reliably even after multiple refreshes.

Also, I'm on FF 107.0 Windows and running 0.286 of this extension.

**Comment by fuddl** [comment]
these are at least two separate issues. I will split them if you don't mind?

**Comment by fuddl** [comment]
## Meta-Problem

> So in the last few weeks the extension has started acting very odd. Really it hasn't worked properly for a while.

I'm not saying there isn't anything to improve. But I need a more specific task or a reproducable scenario. The extension is sometimes lagging behind but I don't know, how to tackle problems like this. I don't think i changed something groundbreaking recently but it might be that there are simply [too many regex patterns](https://w.wiki/63nZ) that have to be queried and processed for every navigation event.

I think this could be improved by scoping them all to a specific domain. So instead of downloading all regex patterns I'd only download those which apply to a specific domain:

![A wikidata statement with a domain qualifier](https://user-images.githubusercontent.com/842548/204845537-61564365-1008-42be-9e34-326a8139d054.png)

## Accidental edits

I agree that [this edit was probably made accidentally](https://www.wikidata.org/w/index.php?title=Q113563433&oldid=1708664757) but there is nothing I can do to prevent that. With the current version it is nessesary to select a property in a dropdown first which should make acciental edits less likely.

## Wrong entities

> * I go to https://twitter.com/hardmaru
> * The side bar shows Q113563433

I cannot reproduce this. if anything Q113563433 should be shown on `https://twitter.com/home`. Which version do you use?

## Social links

> * Links appear to add some social media
> * Clicking on the links does nothing

Are you sure nothing happends? In my case it adds a statement in the sidebar:

![Screenshot 2022-11-30 at 16 57 15](https://user-images.githubusercontent.com/842548/204846627-6640d138-27b8-463a-a195-6b4069824a9f.png)

**Comment by fuddl** [comment]
If you wan't to continue the discussion please do it in a separate issue. Issue compilations like this are painful to handle 😰
