### ISSUE TITLE
Amazon Author ID not being parsed

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#119]
https://www.amazon.com/stores/Chris-Wiggins/author/B0B77TJRHL?

For example, `B0B77TJRHL` should be parsed as the author ID. I think this used to but doesn't seem to now with any authors.

**Comment by loominade** [comment]
I [created a match pattern](https://www.wikidata.org/w/index.php?title=Property%3AP4862&diff=1814668503&oldid=1804720432) for this particular situation. Does it work now?

**Comment by RayBB** [comment]
Working like a charm! Thanks :)
I hope you have some analytics about how much this WD extension is being used because I love it!

**Comment by fuddl** [comment]
@RayBB 

From the extension providers I have an approximate number of users:

Platform | Users
---------|-------
[addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/wikidata/) | 94
[chrome.google](https://chrome.google.com/webstore/detail/wikidata/iijkiilckldlddidhaomggfadfafpdfd?authuser=1) | 109

These numbers however are not trustworthy since I am at least three of these people 😅.

If you make a public edit with the extension, it will appear [in this list](https://www.wikidata.org/w/index.php?days=30&filter=articles&limit=500&tagfilter=wikidata-for-firefox|wikidata-for-web&title=Special:Watchlist&urlversion=2&watchlistview=feed) which I am checking from time to time.

[This list](https://www.wikidata.org/wiki/Special:Tags) contains the accumilated number of all edits _since I started using tags_.  These numbers are:

Tag | Number of edits
----|------------------
[`wikidata-for-firefox`](https://www.wikidata.org/w/index.php?title=Special:RecentChanges&tagfilter=wikidata-for-firefox) | 45521
[`wikidata-for-web`](https://www.wikidata.org/w/index.php?hidebots=1&hideminor=1&hidecategorization=1&tagfilter=wikidata-for-web&limit=500&days=7&title=Special:RecentChanges&urlversion=2) | 19316 


The extension does not collect analytics in any way and I would pretty much hate it if it did. 😬
