### ISSUE TITLE
Add review score by when adding a tripadvisor ID

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#122]
I had to manually say that the review score it imported was by tripadvisor
https://www.wikidata.org/w/index.php?title=Q6940515&action=history

Thanks again for maintaining this great project :)

**Comment by fuddl** [comment]
You mean to say, that the extension should add the qualifier [review score by](https://www.wikidata.org/wiki/Property:P447) to any [review score statement](https://www.wikidata.org/wiki/Property:P444)?

Unfortunatly the tripadvisor website does not hold information on who made the review score. I'm simply reading out the [AggregateRating](https://schema.org/AggregateRating) property:

![The AggregateRating property of Chinatown San Francisco](https://user-images.githubusercontent.com/842548/216265676-dde0a850-4fb0-4537-bc53-78c643fed593.png)
[Chinatown Sctrutured data](https://validator.schema.org/#url=https%3A%2F%2Fwww.tripadvisor.com%2FAttraction_Review-g60713-d108679-Reviews-Chinatown-San_Francisco_California.html)

In theory a website could include aggregate ratings from several other websites or sources. In practice I'm not aware anyone doing that.

Do you have suggestion based on what euristic, the _review score by_ qualifier should be added?

**Comment by RayBB** [comment]
I thought that the review score by would be TripAdvisor but I think you're saying that review score by shouldn't be trip advisor because it is an aggregated rating. 
I don't really know the topic so well but I've seen for example:
https://www.wikidata.org/wiki/Q8694 has:
review score: 3.4/5 (Average)
[review score by](https://www.wikidata.org/wiki/Property:P447): [Trustpilot](https://www.wikidata.org/wiki/Q7848226)
[number of reviews/ratings](https://www.wikidata.org/wiki/Property:P7887): 25,527 user review
[point in time](https://www.wikidata.org/wiki/Property:P585): 20 March 2020

I'm not sure if there's a similar usage somewhere by Trip Advisor reviews but I think they're similar.

Anyway, I don't know too well how wikidata should be in regards to this. I only brought it up because there was a warning on the wikidata page that said review scores should have a review score by. If that's not the case here then I won't worry about it. 

Cheers

**Comment by fuddl** [comment]
> I thought that the review score by would be TripAdvisor but I think you're saying that review score by shouldn't be trip advisor because it is an aggregated rating. 

No, that's not what I tried to say. Let me try it like this:

I try to avoid writing website specific code. I'd rather like a way for the extension to figure out everything by itself. In order to figure out what the value of [review score by](https://www.wikidata.org/wiki/Property:P447) should be, I could for instance:

1. the website was matched by [TripAdvisor ID (P3134)](https://www.wikidata.org/wiki/Property:P3134)
2. [Tripadvisor (Q1770710)](https://www.wikidata.org/wiki/Q1770710) has [Wikidata property (P1687)](https://www.wikidata.org/wiki/Property:P1687) [TripAdvisor ID (P3134)](https://www.wikidata.org/wiki/Property:P3134)
3. [Tripadvisor (Q1770710)](https://www.wikidata.org/wiki/Q1770710) as [has quality (P1552) ](https://www.wikidata.org/wiki/Property:P1552) [user rating (Q80700183)](https://www.wikidata.org/wiki/Q80700183)

so we could assume [Tripadvisor (Q1770710)](https://www.wikidata.org/wiki/Q1770710) might be a good value for the  [review score by](https://www.wikidata.org/wiki/Property:P447) qualifier, If we find [AggregateRating](https://schema.org/AggregateRating)s on this website.

**Comment by fuddl** [comment]
@RayBB or here is a much simpler idea. If it is found on [one of these websites](https://w.wiki/6L3o) the [review score by](https://www.wikidata.org/wiki/Property:P447) property will be set to the corresponding item. How's that?

**Comment by RayBB** [comment]
That seems pretty reasonable to me!

**Comment by fuddl** [comment]
@RayBB if you want to help please make sure websites that offer a user rating appear [in this list](https://w.wiki/6MHD). They'll will need two claims:

* [official website](https://www.wikidata.org/wiki/Property:P856) without folders:
  * ✅ `https://ratings.example.com/`
  * ❌ `https://ratings.example.com/frontpage`
* [has use](https://www.wikidata.org/wiki/Property:P366) →[Q80700183](https://www.wikidata.org/wiki/Q80700183)

**Comment by RayBB** [comment]
Working very well. Thanks! :)
