### ISSUE TITLE
Add Chromium support

### ISSUE THREAD

**Issue by dpriskorn** [fuddl/wd#13]

**Comment by fuddl** [comment]
Chromium does not support the [sidebarAction API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction) which is a critical design element of this extension. I hear there might be polyfills for it?

**Comment by egils-consulting** [comment]
Oh, OK. Thanks for the fast response

**Comment by fuddl** [comment]
@egils-consulting I'd be willing to support it, if someone would feel responsible maintaining it.

**Comment by fuddl** [comment]
I was thinking. It might be feasible to use a good ol popup as a fallback for the sidebarAPI. I have to look into it

**Comment by Stvad** [comment]
+1 to this. implementation-wise - there is a variety of Chrome extensions that do sidebar-like things. Mostly they just inject the sidebar into the page. https://github.com/karlicoss/promnesia is an example

**Comment by Stvad** [comment]
Some initial implementation thoughts on a way to do a gradual migration:
- Create a sidebar overlay to host the content of extension
  - can steal it from https://github.com/WorldBrain/Memex/blob/develop/src/sidebar/SidebarSlider.tsx
- Inside it - have an iframe that opens current pages that are being currently opened in sidebar, allowing most of the extension code remain the same 
  - _Did a PoC of this that works_
  - <img width="872" alt="image" src="https://user-images.githubusercontent.com/81347/146661911-f06c57f0-1052-4fc4-809b-fc5348ee0101.png">
  - Would require changing switching logic to update src of the iframe instead of setting the side-panel url
  - potentially allows for the FF sidebar and in-page sidebar implementations to co-exist (not sure if we should do this)

Misc:
- as discussed on the call, would be nice to gradually migrate to React/alike for frontend implementation

**Comment by Stvad** [comment]
PoC that runs in Chromium in https://github.com/Stvad/wd/tree/chromium

**Comment by Stvad** [comment]
https://chrome.google.com/webstore/detail/wikidata/iijkiilckldlddidhaomggfadfafpdfd
