### ISSUE TITLE
Handle Case Insensitive Identifiers

### ISSUE THREAD

**Issue by derenrich** [fuddl/wd#29]
Twitter usernames (for example) are case insensitive. If I tell the plugin to link a twitter handle to an item and the same handle is already present (but in a different case) it should not add the redundant case. You can detect whether a property is sensitive to case by checking for "has quality" "case insensitivity".

**Comment by fuddl** [comment]
[Twitter username → has quality  → case insensitivity](https://www.wikidata.org/w/index.php?title=Property:P2002&oldid=1488542489#P1552) so 
[https://twitter.com/DerenRich](twitter.com/DerenRich) should resolve to [Q108267155](https://www.wikidata.org/wiki/Q108267155).

Alright, I'll see what I can do.

**Comment by fuddl** [comment]
@derenrich do you have any clue about how to make a case insensitive sparql query?

```js
`
  SELECT ?item
  WHERE {
    ?item wdt:${ prop } "${ id }".
  }
`
```

should I just assume the string in the database is lower case?

```js
`
SELECT ?item
WHERE {
  ?item wdt:${ prop } "${ ci ? id.toLowerCase() : id }".
}
`
````

**Comment by derenrich** [comment]
i think you have to rewrite the query with a filter and downcasing both the search and target strings (or a regex). probably less efficient but it's the only way to be sure.

**Comment by fuddl** [comment]
I'm starting to wonder why we are doing this. Does any part of the twitter api downcase the usernames? Is there a url scheme that only serves the usernames lowercased? If not, why don't we save usernames how they occur? What lowercases them?

**Comment by camelCaseNick** [comment]
We are not doing that at all. Nothing is converted to lower case. On our side, [P2002](https://www.wikidata.org/wiki/Property:P2002) is supposed to store the preferred variant and not the lower case one.

For me it would be "camelCaseNick" not "camelcasenick" nd if you clicked from within Twitter on my profile you'd get https://twitter.com/camelCaseNick. However if you manually navigated to https://twitter.com/camelcasenick Twitter would serve the same profile without a redirect. That is the problem here.

I functioning (though less efficient) query could be:

```
select ?item where {
  ?item wdt:${ prop } ?id.
  filter(lcase(?id) = "${ id.toLowerCase() }")
}
```

**Comment by fuddl** [comment]
> However if you manually navigated to https://twitter.com/camelcasenick Twitter would serve the same profile without a redirect. That is the problem here.

I understand that. But how likely is it? Why should anybody do that?

I found `https://twitter.com/camelCaseNick` using twitters own search. However the page was linked with:

```html
<link href="https://twitter.com/camelcasenick" rel="canonical">
```

So twitter seems to be uncertain, which username they want to show us. I would prefer to store the one that is not lowercased because it contains more information. 🤷

**Comment by derenrich** [comment]
This is a general problem not limited to Twitter

**Comment by fuddl** [comment]
@derenrich Version 0.189 should now resolve case insensitive identifiers case insensitive:
![DerEnrich=derenrich](https://user-images.githubusercontent.com/842548/132396325-36bc8b6d-ee4e-4639-83d3-7aca5a0daef5.png)

If you notice any problems, feel free to reopen this issue

**Comment by derenrich** [comment]
thanks!
