### ISSUE TITLE
switching tabs resets the connector interface which causes accidental duplicate statements

### ISSUE THREAD

**Issue by camelCaseNick** [fuddl/wd#9]
When coming across the same page within minutes, it is possible to accidentally add the same identifier twice. I suppose this could be solved by caching the identifiers that were added for some minutes until the item is query for again, and it could be expected the update would have been picked up.

**Comment by fuddl** [comment]
there already is a cache for precisely this scenario:

You add an external id and load the page in the next view seconds after.

But I think this issue occurs when you instead switch tabs. Id would be nice if  you could make this reproducible. I will definitely look into it.

**Comment by fuddl** [comment]
Let me define the issue here:

## Steps to reproduce

1. open tab with something connectable…
  ![Screen Shot 2020-12-30 at 16 40 51](https://user-images.githubusercontent.com/842548/103364717-cab47d80-4abe-11eb-8f35-eba2c24aa8bf.png)
2.  and another tab to something: 
   ![Screen Shot 2020-12-30 at 16 40 47](https://user-images.githubusercontent.com/842548/103364740-d7d16c80-4abe-11eb-85b1-57d68163a720.png)
3. go to the first tab and connect the thing to wikidata:
   ![Screen Shot 2020-12-30 at 16 40 39](https://user-images.githubusercontent.com/842548/103364763-e4ee5b80-4abe-11eb-818b-65b6c2d4ac43.png)
4. you should now see the wikidata entity in the sidebar
   ![Screen Shot 2020-12-30 at 16 40 44](https://user-images.githubusercontent.com/842548/103364795-f3d50e00-4abe-11eb-87cc-fee0c0d28151.png)
5. push <kbd>CTRL</kbd> and <kbd>Tab ↹</kbd> to get to the second tab
   ![Screen Shot 2020-12-30 at 16 40 47](https://user-images.githubusercontent.com/842548/103364740-d7d16c80-4abe-11eb-85b1-57d68163a720.png)
6. switch back to the first tab
   ![Screen Shot 2020-12-30 at 16 40 47](https://user-images.githubusercontent.com/842548/103364740-d7d16c80-4abe-11eb-85b1-57d68163a720.png)

### Expected result

we should again see wikidata entity that we just connected:
![Screen Shot 2020-12-30 at 16 40 44](https://user-images.githubusercontent.com/842548/103364795-f3d50e00-4abe-11eb-87cc-fee0c0d28151.png)

### Actual result

we see the connect dialog:
![Screen Shot 2020-12-30 at 16 40 51](https://user-images.githubusercontent.com/842548/103364717-cab47d80-4abe-11eb-8f35-eba2c24aa8bf.png)

@camelCaseNick can you confirm, that this is the issue here?

**Comment by camelCaseNick** [comment]
Yes, @fuddl, this is exactly how I came across this issue. I found these ways to get to the “not connected” interface:
* switch to a different tab, that can be resolved to an identifier or item and switch back
* close the wd4ff sidebar and open it again
* change to URL in a meaningless way, e.g. adding a parameter not used by the web server and does not break the regular expression based identifier matching
And yes, simply reloading the page does not affect this.

**Comment by fuddl** [comment]
@camelCaseNick please update to version `0.131` and verify if the issue is solved.

**Comment by camelCaseNick** [comment]
@fuddl I can confirm, that I could not reproduce this issue with `0.131` the way I did with `0.129` and `0.130`. Thank You!

**Comment by fuddl** [comment]
@camelCaseNick thanks for pointing this out

**Comment by camelCaseNick** [comment]
Sorry, I just meant the switching tab type of issue as it was the one I originally meant with this. So the first of the three types to reproduce is fixed with this. But as I mentioned others: The other two still persist. I never came across those by simply using it.

I am not why you would want to close the sidebar to immediately re-open it and whilst doing so have forgotten that you already added the identifier. (You could change the URL by switching languages, though.)

**Comment by fuddl** [comment]
ah, yes. The cache i mentioned only works on the bases of URL → Qid

so if you connect `example.com/en_us/id12345` to `Q123`, the cache will not be invoked for `example.com/de/id12345#content` even though, it points to the same ID. 😕

**Comment by fuddl** [comment]
@camelCaseNick continuing the issue in #10
