### ISSUE TITLE
Adding "Label or alias" should be case-insensitive

### ISSUE THREAD

**Issue by slweeb** [fuddl/wd#95]
"Label or alias" is checked by default and it increases the amount of clicks needed to match an item. It will add a capitalized alias if the label is in lowercase, which is almost always not wanted. It is also a tiny box.

For example: https://www.giantbomb.com/jacket/3055-7088/ or any Fandom article.

**Comment by slweeb** [comment]
That would probably be better. Really love using the extension but this is killing my hands!

**Comment by fuddl** [comment]
But if you really think a website title is absolutly unusable as a label on the whole domain, you should [set the P10999 qualifier of the property to `no value`](https://www.wikidata.org/wiki/Property_talk:P10999#no_value).

**Comment by fuddl** [comment]
these two edits have been made with `.274` with the label checkbox enabled:

* [in this case no label has been added because `jacket = Jacket`](https://www.wikidata.org/w/index.php?title=Q849964&type=revision&diff=1747556994&oldid=1738950275 )
* [in this case a label was added because `The King of Fighters All-Star ≠ The King of Fighters AllStar`](https://www.wikidata.org/w/index.php?title=Q55166899&type=revision&diff=1747559492&oldid=1747559481)
